<a href="https://colab.research.google.com/github/CodingWithBilalkhan/Pytorch-Tutorials/blob/main/2_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TENSOR MATH OPERATIONS

Add, Subtract, Multiply, Divide, Remainders, Exponents
Shorthand and uh, Longhand
Reassignment

In [1]:
import torch
import numpy as np

In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# Numpy Arrays

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.73974841, 0.54271424, 0.81261729, 0.47706568],
       [0.35285924, 0.95740851, 0.35401811, 0.41091166],
       [0.40575291, 0.18831995, 0.46019315, 0.28078767]])

In [5]:
np1.dtype

dtype('float64')

# Tensors

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.3590,  0.0852, -0.8769,  0.2765],
        [ 0.0234, -1.1547,  1.2531, -0.2423],
        [ 2.0933,  0.5199, -1.7758, -0.4516]])

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
# Create tensors out of numpy arrays
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7397, 0.5427, 0.8126, 0.4771],
        [0.3529, 0.9574, 0.3540, 0.4109],
        [0.4058, 0.1883, 0.4602, 0.2808]], dtype=torch.float64)