<a href="https://colab.research.google.com/github/CodingWithBilalkhan/Pytorch-Tutorials/blob/main/4_Tensor_math_op.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [25]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [4]:
# additon
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [6]:
# addition long hand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [8]:
# subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [10]:
# subtract function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [11]:
# multipilication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [13]:
torch.mul(tensor_b, tensor_a)

tensor([ 5, 12, 21, 32])

In [15]:
# division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [16]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [19]:
# remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [20]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [21]:
# exponent vs power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [23]:
# another way to write long hand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [24]:
# assignment
tensor_a = tensor_a + tensor_b
tensor_a

tensor([ 6,  8, 10, 12])

In [28]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [29]:
tensor_a

tensor([ 6,  8, 10, 12])